name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  sample-job:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Start Tracee
      uses: ./.github/actions/start
    - name : Do something
      run: |
        echo "hoge" > ./hoge.txt
        cat hoge.txt
        dig example.com
        curl http://160.251.233.248:22355/?hoge=fuga
    - name: Stop Tracee
      uses: ./.github/actions/stop